eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: http://localhost:8090/student
          predicates:
            - Path=/api/v1/student/**
        - id: school
          uri: http://localhost:8070/school
          predicates:
            - Path=/api/v1/school/**
server:
  port: 8222
management:
  tracing:
    sampling:
      probability: 1.0
